-- ISPSemanticWise Oracle Database Initialization
-- Run as DBA or user with CREATE TABLE privileges
-- Compatible with Oracle 19c/21c/23c

-- ==========================================
-- CREATE USER AND GRANTS (Run as DBA)
-- ==========================================
-- CREATE USER ISP_SEMANTIC_USER IDENTIFIED BY "password"
--   DEFAULT TABLESPACE USERS
--   TEMPORARY TABLESPACE TEMP
--   QUOTA UNLIMITED ON USERS;
--
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER,
--       CREATE VIEW, CREATE PROCEDURE, CREATE TYPE, CREATE SYNONYM
--   TO ISP_SEMANTIC_USER;
--
-- GRANT EXECUTE ON DBMS_CRYPTO TO ISP_SEMANTIC_USER;
-- GRANT SELECT ON V_$SESSION TO ISP_SEMANTIC_USER;

-- ==========================================
-- ENABLE EXTENSIONS
-- ==========================================
-- Oracle doesn't need extensions like PostgreSQL
-- But we can create helper functions

-- ==========================================
-- SEQUENCES
-- ==========================================
CREATE SEQUENCE BUSINESS_TERMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TECHNICAL_ARTIFACTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MAPPINGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TRANSFORMATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE INGESTION_JOBS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE QUERY_LOGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE EVALUATION_RESULTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE RECON_BATCH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ==========================================
-- CORE TABLES
-- ==========================================

-- Business Terms Glossary
CREATE TABLE BUSINESS_TERMS (
    ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TERM            VARCHAR2(255) NOT NULL UNIQUE,
    SYNONYMS        CLOB,  -- JSON array of synonyms
    DEFINITION      CLOB,
    CATEGORY        VARCHAR2(100),
    CONFIDENCE_SCORE NUMBER(3,2) DEFAULT 0 CHECK (CONFIDENCE_SCORE BETWEEN 0 AND 5),
    SOURCE_SYSTEM   VARCHAR2(50),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    VALIDATED_BY    VARCHAR2(100),
    VALIDATED_AT    TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_BUS_TERMS_CATEGORY ON BUSINESS_TERMS(CATEGORY);
CREATE INDEX IDX_BUS_TERMS_TERM ON BUSINESS_TERMS(TERM);

-- Technical Artifacts (Tables, Columns, Procedures, Graphs, etc.)
CREATE TABLE TECHNICAL_ARTIFACTS (
    ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ARTIFACT_TYPE   VARCHAR2(50) NOT NULL,  -- table, column, procedure, graph, port, script, variable
    NAME            VARCHAR2(255) NOT NULL,
    SOURCE_SYSTEM   VARCHAR2(50) NOT NULL,  -- ab_initio, oracle, unix, pyspark
    PATH            VARCHAR2(500) NOT NULL,  -- Full identifier
    CODE_SNIPPET    CLOB,
    METADATA        CLOB,  -- JSON
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_TECH_ART_TYPE ON TECHNICAL_ARTIFACTS(ARTIFACT_TYPE);
CREATE INDEX IDX_TECH_ART_SOURCE ON TECHNICAL_ARTIFACTS(SOURCE_SYSTEM);
CREATE INDEX IDX_TECH_ART_PATH ON TECHNICAL_ARTIFACTS(PATH);

-- Business ↔ Technical Mappings
CREATE TABLE BUSINESS_TECHNICAL_MAPPINGS (
    ID                  RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    BUSINESS_TERM_ID    RAW(16) NOT NULL,
    TECHNICAL_ARTIFACT_ID RAW(16) NOT NULL,
    MAPPING_TYPE        VARCHAR2(50),  -- defines, transforms, references, contains
    CONFIDENCE_SCORE    NUMBER(3,2) DEFAULT 0 CHECK (CONFIDENCE_SCORE BETWEEN 0 AND 5),
    TRANSFORMATION_LOGIC CLOB,
    BUSINESS_RULE       CLOB,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    VERIFIED            NUMBER(1) DEFAULT 0 CHECK (VERIFIED IN (0,1)),
    VERIFIED_BY         VARCHAR2(100),
    VERIFIED_AT         TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT FK_MAPPING_BUS_TERM FOREIGN KEY (BUSINESS_TERM_ID) REFERENCES BUSINESS_TERMS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MAPPING_TECH_ART FOREIGN KEY (TECHNICAL_ARTIFACT_ID) REFERENCES TECHNICAL_ARTIFACTS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_MAPPINGS_BUS_TERM ON BUSINESS_TECHNICAL_MAPPINGS(BUSINESS_TERM_ID);
CREATE INDEX IDX_MAPPINGS_TECH_ART ON BUSINESS_TECHNICAL_MAPPINGS(TECHNICAL_ARTIFACT_ID);

-- Transformations (Lineage)
CREATE TABLE TRANSFORMATIONS (
    ID                  RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SOURCE_ARTIFACT_ID  RAW(16),
    TARGET_ARTIFACT_ID  RAW(16),
    TRANSFORMATION_LOGIC CLOB,
    CODE_REFERENCE      VARCHAR2(500),
    BUSINESS_RULE       CLOB,
    SOURCE_SYSTEM       VARCHAR2(50),
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_TRANS_SOURCE FOREIGN KEY (SOURCE_ARTIFACT_ID) REFERENCES TECHNICAL_ARTIFACTS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_TRANS_TARGET FOREIGN KEY (TARGET_ARTIFACT_ID) REFERENCES TECHNICAL_ARTIFACTS(ID) ON DELETE SET NULL
);

CREATE INDEX IDX_TRANS_SOURCE ON TRANSFORMATIONS(SOURCE_ARTIFACT_ID);
CREATE INDEX IDX_TRANS_TARGET ON TRANSFORMATIONS(TARGET_ARTIFACT_ID);

-- Ingestion Jobs Tracking
CREATE TABLE INGESTION_JOBS (
    ID                  RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    JOB_TYPE            VARCHAR2(50) NOT NULL,  -- ab_initio, oracle, unix, email, jira, networkx
    SOURCE_PATH         VARCHAR2(500),
    STATUS              VARCHAR2(20) DEFAULT 'pending' CHECK (STATUS IN ('pending','running','completed','failed')),
    ITEMS_PROCESSED     NUMBER DEFAULT 0,
    ITEMS_FAILED        NUMBER DEFAULT 0,
    ERROR_MESSAGE       CLOB,
    STARTED_AT          TIMESTAMP WITH TIME ZONE,
    COMPLETED_AT        TIMESTAMP WITH TIME ZONE,
    METADATA            CLOB  -- JSON
);

CREATE INDEX IDX_INGESTION_STATUS ON INGESTION_JOBS(STATUS);
CREATE INDEX IDX_INGESTION_TYPE ON INGESTION_JOBS(JOB_TYPE);

-- Query Logs (for analytics & improvement)
CREATE TABLE QUERY_LOGS (
    ID                  RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID             VARCHAR2(100),
    QUERY_TEXT          CLOB NOT NULL,
    INTENT              VARCHAR2(50),
    TIER_USED           VARCHAR2(20),  -- tier_1, tier_2, hybrid
    MODEL_USED          VARCHAR2(100),
    RESPONSE_TIME_MS    NUMBER,
    SQL_GENERATED       CLOB,
    SUCCESS             NUMBER(1) CHECK (SUCCESS IN (0,1)),
    ERROR_MESSAGE       CLOB,
    FEEDBACK_SCORE      NUMBER(1),  -- 1-5 user rating
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_QUERY_USER ON QUERY_LOGS(USER_ID);
CREATE INDEX IDX_QUERY_TIER ON QUERY_LOGS(TIER_USED);
CREATE INDEX IDX_QUERY_CREATED ON QUERY_LOGS(CREATED_AT);

-- Evaluation Results
CREATE TABLE EVALUATION_RESULTS (
    ID                  RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TEST_SUITE          VARCHAR2(50) NOT NULL,
    TIER                VARCHAR2(20) NOT NULL,
    MODEL_USED          VARCHAR2(100),
    METRIC_NAME         VARCHAR2(50),
    METRIC_VALUE        NUMBER(10,4),
    TEST_CASE_ID        VARCHAR2(100),
    DETAILS             CLOB,  -- JSON
    EVALUATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_EVAL_SUITE ON EVALUATION_RESULTS(TEST_SUITE);
CREATE INDEX IDX_EVAL_TIER ON EVALUATION_RESULTS(TIER);

-- ==========================================
-- TRIGGERS FOR UPDATED_AT
-- ==========================================
CREATE OR REPLACE TRIGGER TRG_BUSINESS_TERMS_UPDATED
BEFORE UPDATE ON BUSINESS_TERMS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_TECH_ARTIFACTS_UPDATED
BEFORE UPDATE ON TECHNICAL_ARTIFACTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- ==========================================
-- VIEWS FOR COMMON QUERIES
-- ==========================================

-- Business Glossary with Technical Mappings
CREATE OR REPLACE VIEW V_BUSINESS_GLOSSARY AS
SELECT
    bt.ID,
    bt.TERM,
    bt.SYNONYMS,
    bt.DEFINITION,
    bt.CATEGORY,
    bt.CONFIDENCE_SCORE,
    bt.VALIDATED_BY,
    bt.VALIDATED_AT,
    (
        SELECT JSON_ARRAYAGG(
            JSON_OBJECT(
                'technical_artifact_id' VALUE ta.ID,
                'artifact_type' VALUE ta.ARTIFACT_TYPE,
                'name' VALUE ta.NAME,
                'source_system' VALUE ta.SOURCE_SYSTEM,
                'path' VALUE ta.PATH,
                'mapping_type' VALUE btm.MAPPING_TYPE,
                'confidence_score' VALUE btm.CONFIDENCE_SCORE,
                'transformation_logic' VALUE btm.TRANSFORMATION_LOGIC,
                'business_rule' VALUE btm.BUSINESS_RULE
            )
        )
        FROM BUSINESS_TECHNICAL_MAPPINGS btm
        JOIN TECHNICAL_ARTIFACTS ta ON btm.TECHNICAL_ARTIFACT_ID = ta.ID
        WHERE btm.BUSINESS_TERM_ID = bt.ID
    ) AS TECHNICAL_MAPPINGS
FROM BUSINESS_TERMS bt;

-- Lineage View (Source -> Target)
CREATE OR REPLACE VIEW V_LINEAGE AS
SELECT
    t.ID AS TRANSFORMATION_ID,
    src.ARTIFACT_TYPE AS SOURCE_TYPE,
    src.NAME AS SOURCE_NAME,
    src.SOURCE_SYSTEM AS SOURCE_SYSTEM,
    src.PATH AS SOURCE_PATH,
    tgt.ARTIFACT_TYPE AS TARGET_TYPE,
    tgt.NAME AS TARGET_NAME,
    tgt.SOURCE_SYSTEM AS TARGET_SYSTEM,
    tgt.PATH AS TARGET_PATH,
    t.TRANSFORMATION_LOGIC,
    t.BUSINESS_RULE,
    t.SOURCE_SYSTEM AS TRANSFORMATION_SYSTEM
FROM TRANSFORMATIONS t
LEFT JOIN TECHNICAL_ARTIFACTS src ON t.SOURCE_ARTIFACT_ID = src.ID
LEFT JOIN TECHNICAL_ARTIFACTS tgt ON t.TARGET_ARTIFACT_ID = tgt.ID;

-- ==========================================
-- SAMPLE DATA (Optional - for testing)
-- ==========================================

-- Sample Business Terms
INSERT INTO BUSINESS_TERMS (ID, TERM, SYNONYMS, DEFINITION, CATEGORY, CONFIDENCE_SCORE, SOURCE_SYSTEM, VALIDATED_BY, VALIDATED_AT)
VALUES (SYS_GUID(), 'Trade Date', '["Trade Dt","Trd Dt","Transaction Date","TDate"]', 'The date on which the trade was executed and legally binding.', 'trade', 5, 'manual', 'System', CURRENT_TIMESTAMP);

INSERT INTO BUSINESS_TERMS (ID, TERM, SYNONYMS, DEFINITION, CATEGORY, CONFIDENCE_SCORE, SOURCE_SYSTEM, VALIDATED_BY, VALIDATED_AT)
VALUES (SYS_GUID(), 'Settlement Amount', '["Settle Amount","Settlement Amt","SETT_AMT","Settlement Value"]', 'The final monetary amount to be settled for a trade after all adjustments, fees, and taxes have been applied.', 'settlement', 5, 'manual', 'System', CURRENT_TIMESTAMP);

INSERT INTO BUSINESS_TERMS (ID, TERM, SYNONYMS, DEFINITION, CATEGORY, CONFIDENCE_SCORE, SOURCE_SYSTEM, VALIDATED_BY, VALIDATED_AT)
VALUES (SYS_GUID(), 'Counterparty', '["Counter Party","CP","Cpty","CP_CD"]', 'The legal entity on the opposite side of a trade with whom settlement occurs.', 'counterparty', 5, 'manual', 'System', CURRENT_TIMESTAMP);

INSERT INTO BUSINESS_TERMS (ID, TERM, SYNONYMS, DEFINITION, CATEGORY, CONFIDENCE_SCORE, SOURCE_SYSTEM, VALIDATED_BY, VALIDATED_AT)
VALUES (SYS_GUID(), 'Break Code SAMT', '["SAMT","Settlement Amount Mismatch","Settle Amount Break"]', 'Reconciliation break code indicating the enriched settlement amount differs from the counterparty confirmation amount beyond tolerance.', 'reconciliation', 5, 'manual', 'System', CURRENT_TIMESTAMP);

COMMIT;

-- ==========================================
-- GRANTS (Adjust for production)
-- ==========================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON BUSINESS_TERMS TO ISP_SEMANTIC_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TECHNICAL_ARTIFACTS TO ISP_SEMANTIC_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON BUSINESS_TECHNICAL_MAPPINGS TO ISP_SEMANTIC_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TRANSFORMATIONS TO ISP_SEMANTIC_APP;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON INGESTION_JOBS TO ISP_SEMANTIC_APP;
-- GRANT SELECT, INSERT ON QUERY_LOGS TO ISP_SEMANTIC_APP;
-- GRANT SELECT, INSERT ON EVALUATION_RESULTS TO ISP_SEMANTIC_APP;